### ISSUE TITLE
Add legend feature

### ISSUE THREAD

**Issue by eliecharra** [egeloen/ivory-google-map#90] opened 2014-09-23 19:18 UTC
Why not adding a legend feature ?
I've made a PR based on this tutorial :
https://developers.google.com/maps/tutorials/customizing/adding-a-legend

![terradona local test php](https://cloud.githubusercontent.com/assets/6154987/4378250/32b649e4-4356-11e4-9fdb-35c4be59146f.png)

**Comment by egeloen** [comment] 2016-08-17 10:28
Closing as duplicate of #160

**Closed by egeloen** 2016-08-17 10:28 UTC
Labels: enhancement
